package pitest

/**
 * Parses PITest mutation testing output to extract relevant metrics.
 */
class PitestReportParser {

    /**
     * Extracts the mutation testing score from the provided output string.
     *
     * @param output The output string generated by the PITest execution, containing the mutation test results.
     * @return The mutation score percentage as an integer, or 0 if the score cannot be parsed.
     */
    fun getMutationScore(output: String): Int {
        val regex = """>> Generated \d+ mutations Killed \d+ \((\d+)%\)""".toRegex()
        return regex.find(output)?.groupValues?.get(1)?.toInt() ?: 0
    }
}
